### ISSUE TITLE
Error running `update`

### ISSUE THREAD

**Issue by jbriales** [rejuvyesh/arbtt-graph#6]
Hi!
I just started using `arbtt` and your visualization solution (neat work!).
I think I followed your instructions properly but here is what I do for now and what I get:

```
$ cd Apps && git clone https://github.com/rejuvyesh/arbtt-graph.git
$ cd arbtt-graph
$ ./update
Processing data [===========================] 100%
Processing data [===========================] 100%
Traceback (most recent call last):
  File "readArbttStats.py", line 146, in <module>
    main()
  File "readArbttStats.py", line 143, in main
    dailyUsage(dailyCsv, minuteCsv, categoryName)
  File "readArbttStats.py", line 78, in dailyUsage
    tag = row[1].split(':')[1]
IndexError: list index out of range
```

Thanks!

**Comment by jbriales** [comment]
I found a fix and explained the issue [here](https://github.com/rejuvyesh/arbtt-graph/pull/7).
